// Requete telnet GET
GET / HTTP/1.1
HOST: localhost:8080
Connection: close

// Requete telnet POST sans content
POST /cgi/py/response.py HTTP/1.1
Host: example.com

// Requete telnet POST avec content
POST /cgi/py/response.py HTTP/1.1
Host: localhost:8080
Content-Length: 34
Content-Type: application/x-www-form-urlencoded

color=haha&meal=haha&season=haha

// Requete telnet POST cgi avec chunk
POST /cgi/py/response.py HTTP/1.1
Transfer-encoding: chunked
Host: server.com

b
color=haha&

9
meal=dsf&

c
season=dsgd&

0

// Requete method unknown
UNKNOWN www/files_to_delete/text5.txt HTTP/1.1
Host: localhost:8080
Connection: close


//