POST /cgi HTTP/1.1
Transfer-encoding: chunked
Host: example.com

a
color=haha

8
meal=dsf

b
season=dsgd

0



POST /cgi/py/response.py HTTP/1.1
Transfer-encoding: chunked
Host: example.com

b
color=haha&

9
meal=dsf&

c
season=dsgd&

0

