cas normal : 1.GET + query
			 2.POST + body

cas erreurs : 3.GET avec body
			  4.GET avec nimp en query
			  5.POST sans body
			  6.POST avec nimp en body

1. result --> reponse normal
GET /cgi/py/response.py?color=czx&meal=meazxczxvl&season=zxv HTTP/1.1
Transfer-encoding: chunked
Host: example.com

0

2. result --> reponse normal
POST /cgi/py/response.py HTTP/1.1
Transfer-encoding: chunked
Host: example.com

b
color=haha&

9
meal=dsf&

c
season=dsgd&

0


3. result --> bad request
GET /cgi/py/response.py HTTP/1.1
Transfer-encoding: chunked
Host: example.com

b
color=haha&

9
meal=dsf&

c
season=dsgd&

0


4. result --> reponse renvoyee mais sans les infos
GET /cgi/py/response.py?sdFhsdlufhuis&&^*^%dashdvsa HTTP/1.1
Transfer-encoding: chunked
Host: example.com

0


4. autre cas result --> bad request
GET sdFhsdlufhuis&&^*^%dashdvsa HTTP/1.1
Transfer-encoding: chunked
Host: example.com

0

5. result --> reponse renvoyee mais sans les infos
POST /cgi/py/response.py HTTP/1.1
Transfer-encoding: chunked
Host: example.com

0


6.
POST /cgi/py/response.py HTTP/1.1
Transfer-encoding: chunked
Host: example.com

&%%*b
color=haha&

9
meal=dsf&

c
season=dsgd&

0



DELETE /www/files_to_delete/text4.txt HTTP/1.1
Host: localhost:8080
Connection: close


UNKNOWN www/files_to_delete/text5.txt HTTP/1.1
Host: localhost:8080
Connection: close


